### ISSUE TITLE
Tables are not rendered in Section 4.3

### ISSUE THREAD

**Issue by ekothe** [crsh/papaja_man#6]
Section 4.3 demonstrates apa_table() and includes a demonstration (not fully described) of the use of table captions and notes using bookdown format. However, these do not appear to be rendered in the bookdown version of the manual at https://crsh.github.io/papaja_man/reporting.html#tables

![Screen Shot 2019-07-07 at 12 58 31 PM](https://user-images.githubusercontent.com/11023525/60767342-05e71380-a0b7-11e9-9c73-cbdd98014403.png)

**Comment by ekothe** [comment]
@crsh There seem to be a number of errors in this subsection. I think I've solved most of them - but one is that dplyr is not previously called in the manual which was causing build to fail if the chunk is evaluated. Do you have a preference for the placement of this library call? (i.e. it would be placed in this chunk but I know most people prefer to put library calls in a single place in a .rmd - do you have a preference?)

**Comment by crsh** [comment]
Thanks for jumping on this. Parts of the manual are currently a copy-paste desert based on workshop slides. 😓 

I think I've tried to include library calls in `index.Rmd`. If you feel like it's more appropriate to have them close to the code where the package functions are used, that's also fine with me.
