### ISSUE TITLE
citation (re)ordering

### ISSUE THREAD

**Issue by tomstafford** [crsh/papaja_man#9]
https://github.com/crsh/papaja_man/edit/master/03-writing.Rmd states

> Note that pre- and postfixes are bound to the enclosed citation, not to the set of all citations. Hence, a prefix will be reorder together with its citation, which may be undesirable. For example, [e.g., @james_1890; @bem_2011] yields (e.g., James, 1890; Bem, 2011). There is no way to prevent this behavior, so mind the alphabetical order of citations.

I think there is a typo here - the rendered citation should be (Bem, 2011; e.g., James, 1890) ie reordered alphabetically

**Comment by crsh** [comment]
Indeed, thanks for pointing this out! I just found out that this reflects a change that was recently introduced to `pandoc-citeproc`. [Citations with prefixes are no longer subject to citation-style sorting](https://github.com/jgm/pandoc-citeproc/blob/master/changelog#L266). I have updated the documentation accordingly: https://github.com/crsh/papaja_man/commit/6c9356719b01c0b0a747511eaed4ce716ba8b1c7
